import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const content = {
  ar: {
    brand: 'معاذ حماد', tag: 'للمحاسبة والتدقيق', nav: ['الرئيسية', 'من نحن', 'الخدمات', 'من نخدم', 'الرؤى', 'تواصل'],
    book: 'احجز استشارة', more: 'اكتشف خدماتنا', whatsapp: 'تواصل عبر واتساب', homeTitle: 'محاسبة واضحة تدعم قرارك القادم.',
    homeDesc: 'خدمات محاسبة وتدقيق عملية للشركات في دولة الإمارات، تمنحك أرقاماً موثوقة ورؤية أوضح للنمو.',
    heroEyebrow: 'شريكك المالي للأعمال في الإمارات', heroTitle: 'نحوّل أرقام عملك إلى <em>ثقة ووضوح.</em>',
    heroText: 'من تنظيم الدفاتر إلى التقارير المالية، نمنح أصحاب الأعمال في الإمارات دعماً مالياً مفهوماً ودقيقاً — بلا تعقيد.',
    trust: [['الدقة', 'تفاصيل صحيحة لقرارات متوازنة'], ['الوضوح', 'تقارير تتحدث بلغة الأعمال'], ['تركيز الإمارات', 'دعم يتماشى مع واقع السوق'], ['الموثوقية', 'التزام مستمر يمكنك الاعتماد عليه']],
    painTitle: 'هل تُدير العمل، أم تبحث عن أرقامه؟', painText: 'عندما تتراكم الفواتير وتتأخر التسويات، يصبح اتخاذ القرار أصعب مما يجب. نضع نظاماً بسيطاً يترك لك مساحة للعمل والنمو.',
    pain: ['مبيعات يومية بلا صورة واضحة للربحية', 'مصروفات وفواتير تحتاج إلى تنظيم منتظم', 'تقارير متأخرة لا تساعدك على التصرف في الوقت المناسب'],
    servicesTitle: 'دعم مالي مناسب لمرحلة عملك', servicesText: 'خدمات عملية تبدأ من الأساسيات وتبني الثقة في كل رقم.',
    services: [['خدمات المحاسبة', 'إمساك الدفاتر، التسويات، وإعداد تقارير مالية تساعدك على فهم أدائك.'], ['خدمات التدقيق', 'مراجعة منظمة ومهنية تعزز موثوقية المعلومات المالية.'], ['الدعم المالي والتجاري', 'رؤية عملية للسيولة والميزانيات والقرارات اليومية.']],
    serveTitle: 'نفهم طريقة عملك', serveText: 'نصمم الدعم المالي حول واقع عملياتك، لا حول قالب عام.', audiences: ['المطاعم', 'المخابز', 'الشركات الصغيرة', 'الشركات الناشئة', 'الشركات المتنامية'],
    whyTitle: 'شراكة مالية هادئة وواضحة', whyText: 'لا نكتفي بإتمام المهام. نرتب الأولويات، نفسّر الأرقام، ونبني أساساً أفضل للخطوة التالية.', process: [['01', 'نفهم', 'نبدأ بسماع واقع عملك وأهدافك.'], ['02', 'نقيّم', 'نراجع البيانات والعمليات الحالية بوضوح.'], ['03', 'ندعم', 'ننفذ نظاماً مالياً مناسباً ومستداماً.'], ['04', 'تنمو بثقة', 'نقدّم رؤية تساعدك على التحرك بوعي.']],
    insightsTitle: 'رؤى تساعدك على اتخاذ قرار أفضل', faqTitle: 'أسئلة شائعة', ctaTitle: 'لنضع أرقام عملك في مكانها الصحيح.', ctaText: 'ابدأ بمحادثة بسيطة حول احتياجاتك المحاسبية أو التدقيقية في الإمارات.',
    footerText: 'خدمات محاسبة وتدقيق عملية لأصحاب الأعمال في دولة الإمارات.', allRights: 'جميع الحقوق محفوظة.', privacy: 'سياسة الخصوصية', disclaimer: 'إخلاء المسؤولية',
    aboutTitle: 'المحاسبة الدقيقة ليست رفاهية. إنها أساس القرار.', aboutText: 'معاذ حماد للمحاسبة والتدقيق يقدم دعماً مالياً واضحاً ومهنياً للشركات التي تحتاج إلى فهم أرقامها، لا مجرد استلامها.',
    aboutCards: [['وضوح في كل خطوة', 'نشرح ما يهمك بلغة مباشرة، مع تفاصيل تدعم القرار.'], ['منهج منظم', 'نبني العمليات على الدقة والاستمرارية وقابلية المتابعة.'], ['تركيز على العمل', 'الدعم المالي مصمم ليخدم واقع عملك في دولة الإمارات.']],
    servicesPageTitle: 'خدمات تبدأ من التفاصيل وتنتهي برؤية أوضح.', servicesPageText: 'اختر مستوى الدعم الذي يناسب عملياتك اليوم، مع مرونة للنمو غداً.',
    servePageTitle: 'دعم مالي يفهم تحديات قطاعك.', insightPageTitle: 'رؤى مالية عملية لأعمال الإمارات.', contactTitle: 'لنبدأ محادثة مفيدة.', contactText: 'شاركنا احتياجك وسنتواصل معك لمناقشة الخطوة الأنسب.', send: 'أرسل الطلب', name: 'الاسم الكامل', business: 'اسم الشركة', email: 'البريد الإلكتروني', phone: 'رقم الهاتف', message: 'كيف يمكننا المساعدة؟', sent: 'شكراً لك. تم استلام طلبك وسنتواصل معك قريباً.',
    search: 'ابحث في المقالات...', noResults: 'لم نجد مقالات مطابقة.', read: 'اقرأ المقال', backHome: 'العودة للرئيسية', notFound: 'الصفحة التي تبحث عنها غير متاحة أو ربما تم نقلها.',
    faq: [['هل تقدمون خدمات للشركات الصغيرة في دبي؟', 'نعم. نقدّم دعماً عملياً للشركات الصغيرة في دبي والإمارات، مع التركيز على تنظيم المعلومات المالية وتحسين وضوحها.'], ['ما الفرق بين المحاسبة والتدقيق؟', 'المحاسبة تنظم وتعرض المعاملات المالية، بينما يراجع التدقيق موثوقية المعلومات والعمليات المرتبطة بها.'], ['كيف أبدأ؟', 'ابدأ بحجز استشارة. سنفهم متطلبات عملك ونقترح نطاق الدعم المناسب.']],
  },
  en: {
    brand: 'Moath Hammad', tag: 'Accounting & Auditing', nav: ['Home', 'About', 'Services', 'Who We Serve', 'Insights', 'Contact'],
    book: 'Book a Consultation', more: 'Explore Services', whatsapp: 'WhatsApp Us', homeTitle: 'Clear accounting for your next business decision.', homeDesc: 'Practical accounting and auditing services for UAE businesses, giving you reliable figures and a clearer path to growth.',
    heroEyebrow: 'Financial partner for UAE businesses', heroTitle: 'Turn your numbers into <em>clarity and confidence.</em>', heroText: 'From organised books to meaningful financial reporting, we give UAE business owners accurate, understandable support — without the complexity.',
    trust: [['Accuracy', 'Reliable details for balanced decisions'], ['Clarity', 'Reports that speak your business language'], ['UAE Focus', 'Support grounded in the local market'], ['Reliability', 'Consistent care you can count on']],
    painTitle: 'Running the business, or chasing its numbers?', painText: 'When receipts pile up and reconciliations wait, decisions become harder than they need to be. We bring order that creates room to run and grow.',
    pain: ['Daily sales without a clear view of profitability', 'Expenses and invoices needing regular structure', 'Late reports that cannot support timely action'],
    servicesTitle: 'Financial support for your stage of business', servicesText: 'Practical services that begin with the essentials and build confidence in every number.',
    services: [['Accounting Services', 'Bookkeeping, reconciliations and financial reporting that help you understand performance.'], ['Auditing Services', 'Structured, professional review that strengthens confidence in financial information.'], ['Financial & Business Support', 'Practical perspective on cash flow, budgets and day-to-day decisions.']],
    serveTitle: 'We understand how you work', serveText: 'Our financial support is shaped around the reality of your operations — not a generic template.', audiences: ['Restaurants', 'Bakeries', 'Small Businesses', 'Startups', 'Growing Companies'],
    whyTitle: 'A calm, clear financial partnership', whyText: 'We do more than complete tasks. We set priorities, explain the numbers and create a stronger foundation for what comes next.', process: [['01', 'Understand', 'We start by listening to your business reality and goals.'], ['02', 'Assess', 'We review the current data and processes with care.'], ['03', 'Support', 'We implement a financial system that fits and lasts.'], ['04', 'Grow with confidence', 'We provide insight that supports informed action.']],
    insightsTitle: 'Insights for better business decisions', faqTitle: 'Frequently asked questions', ctaTitle: 'Let’s put your business numbers in the right place.', ctaText: 'Start with a simple conversation about your accounting or auditing needs in the UAE.',
    footerText: 'Practical accounting and auditing services for UAE business owners.', allRights: 'All rights reserved.', privacy: 'Privacy Policy', disclaimer: 'Disclaimer',
    aboutTitle: 'Accurate accounting is not a luxury. It is the basis for a decision.', aboutText: 'Moath Hammad Accounting & Auditing gives businesses the clear, professional financial support they need to understand their numbers, not simply receive them.',
    aboutCards: [['Clarity at every step', 'We explain what matters in direct language, with detail that supports decisions.'], ['A structured approach', 'We build around accuracy, consistency and easy follow-through.'], ['Business-led support', 'Financial support designed around your UAE operating reality.']],
    servicesPageTitle: 'Services that begin with detail and end in clearer direction.', servicesPageText: 'Choose support that fits your operations today, with the flexibility to grow tomorrow.',
    servePageTitle: 'Financial support that understands your sector.', insightPageTitle: 'Practical financial insights for UAE businesses.', contactTitle: 'Let’s start a useful conversation.', contactText: 'Tell us what you need and we will be in touch to discuss the right next step.', send: 'Send Request', name: 'Full name', business: 'Business name', email: 'Email address', phone: 'Phone number', message: 'How can we help?', sent: 'Thank you. Your request has been received and we will be in touch soon.',
    search: 'Search articles...', noResults: 'No matching articles found.', read: 'Read article', backHome: 'Return home', notFound: 'The page you are looking for is unavailable or may have moved.',
    faq: [['Do you support small businesses in Dubai?', 'Yes. We offer practical support for small businesses in Dubai and across the UAE, focused on organised and clearer financial information.'], ['What is the difference between accounting and auditing?', 'Accounting organises and presents financial activity; auditing reviews the reliability of financial information and related processes.'], ['How do I get started?', 'Book a consultation. We will understand your requirements and suggest the appropriate scope of support.']],
  }
};

const routes = ['/', '/about', '/services', '/who-we-serve', '/insights', '/contact'];
const paths = { 0: '/', 1: '/about', 2: '/services', 3: '/who-we-serve', 4: '/insights', 5: '/contact' };
const icons = { arrow:'→', check:'✓', menu:'☰', close:'×', search:'⌕', phone:'◌' };
function Link({to, children, className='', onClick}) { return <a href={'#'+to} className={className} onClick={onClick}>{children}</a> }
function SEO({title, description, lang, type='website', crumbs=[]}) { useEffect(() => { const full=`${title} | Moath Hammad Accounting & Auditing`; document.title=full; document.documentElement.lang=lang; document.documentElement.dir=lang==='ar'?'rtl':'ltr'; const base='https://moathhammad.ae'; const canonical=base+(location.hash.slice(1)||'/'); const set=(n,v,p='name')=>{let e=document.head.querySelector(`meta[${p}="${n}"]`);if(!e){e=document.createElement('meta');e.setAttribute(p,n);document.head.append(e)}e.content=v}; set('description',description);set('og:title',full,'property');set('og:description',description,'property');set('og:type',type,'property');set('og:url',canonical,'property');set('twitter:card','summary_large_image'); let c=document.head.querySelector('link[rel="canonical"]');if(!c){c=document.createElement('link');c.rel='canonical';document.head.append(c)}c.href=canonical; const schema=[{'@context':'https://schema.org','@type':['Organization','ProfessionalService'],name:'Moath Hammad Accounting & Auditing',description,url:base,areaServed:{'@type':'Country',name:'United Arab Emirates'},serviceType:['Accounting services UAE','Auditing firm UAE','Financial reporting UAE']}, crumbs.length&&{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:crumbs.map((x,i)=>({'@type':'ListItem',position:i+1,name:x.name,item:base+x.path}))}].filter(Boolean); let el=document.getElementById('page-schema');if(!el){el=document.createElement('script');el.type='application/ld+json';el.id='page-schema';document.head.append(el)}el.textContent=JSON.stringify(schema)},[title,description,lang,type,crumbs]); return null }
function Button({to, children, secondary=false}) { return <Link to={to} className={'button '+(secondary?'button-secondary':'')}>{children}<span aria-hidden>{icons.arrow}</span></Link> }
function Header({t, lang, setLang}) { const [open,setOpen]=useState(false); return <header className="site-header"><div className="nav-wrap"><Link to="/" className="logo" onClick={()=>setOpen(false)}><span className="logo-mark">MH</span><span><b>{t.brand}</b><small>{t.tag}</small></span></Link><button className="menu-toggle" aria-label="Toggle navigation" onClick={()=>setOpen(!open)}>{open?icons.close:icons.menu}</button><nav className={open?'open':''} aria-label="Primary navigation">{t.nav.map((x,i)=><Link key={x} to={paths[i]} onClick={()=>setOpen(false)}>{x}</Link>)}<button className="language" onClick={()=>setLang(lang==='ar'?'en':'ar')} aria-label="Change language">AR <i/> EN</button><Button to="/contact">{t.book}</Button></nav></div></header> }
function Footer({t}) { return <footer><div className="footer-grid"><div><Link to="/" className="logo"><span className="logo-mark">MH</span><span><b>{t.brand}</b><small>{t.tag}</small></span></Link><p>{t.footerText}</p></div><div><h3>Navigate</h3><Link to="/about">{t.nav[1]}</Link><Link to="/services">{t.nav[2]}</Link><Link to="/insights">{t.nav[4]}</Link></div><div><h3>Contact</h3><a href="tel:[PHONE NUMBER]">[PHONE NUMBER]</a><a href="mailto:[EMAIL]">[EMAIL]</a><span>[OFFICE ADDRESS]</span></div></div><div className="footer-bottom"><span>© 2026 {t.brand}. {t.allRights}</span><span><a href="#/privacy">{t.privacy}</a> · <a href="#/disclaimer">{t.disclaimer}</a></span></div></footer> }
function SectionHead({eyebrow,title,text,center=false}) { return <div className={'section-head '+(center?'center':'')}><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{text&&<p>{text}</p>}</div> }
const articles=[
 {slug:'cash-flow-basics',cat:'Accounting Tips',title:'Cash flow basics: a clearer weekly view for your business',excerpt:'A simple rhythm for seeing what is coming in, going out and what needs attention.'},
 {slug:'restaurant-numbers',cat:'Restaurant Accounting',title:'The numbers restaurant owners should review each week',excerpt:'Focus your attention on the measures that make your daily operations easier to manage.'},
 {slug:'reporting-uae',cat:'UAE Business Finance',title:'Why timely financial reporting matters for UAE businesses',excerpt:'Reliable reporting provides the visibility needed for calmer, more informed decisions.'}
];
function Hero({t}) { return <><section className="hero"><div className="hero-copy"><span className="eyebrow">{t.heroEyebrow}</span><h1 dangerouslySetInnerHTML={{__html:t.heroTitle}} /><p>{t.heroText}</p><div className="actions"><Button to="/contact">{t.book}</Button><Button secondary to="/services">{t.more}</Button></div></div><div className="hero-art" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="metric-card"><small>FINANCIAL CLARITY</small><b>01</b><span>Built around your business</span></div><div className="line line-a"/><div className="line line-b"/></div></section><section className="trust-strip">{t.trust.map(([title,text])=><div key={title}><strong>{title}</strong><span>{text}</span></div>)}</section></> }
function Home({t,lang}) { const [faq,setFaq]=useState(null); useEffect(()=>{const el=document.getElementById('faq-schema');if(!el){const s=document.createElement('script');s.id='faq-schema';s.type='application/ld+json';document.head.append(s); } document.getElementById('faq-schema').textContent=JSON.stringify({'@context':'https://schema.org','@type':'FAQPage',mainEntity:t.faq.map(x=>({'@type':'Question',name:x[0],acceptedAnswer:{'@type':'Answer',text:x[1]}}))})},[t]); return <><SEO lang={lang} title={t.homeTitle} description={t.homeDesc} crumbs={[{name:'Home',path:'/'}]}/><Hero t={t}/><main><section className="section pain"><div className="pain-art"><span>UAE</span><div/></div><div><SectionHead eyebrow="BUILT FOR BUSINESS OWNERS" title={t.painTitle} text={t.painText}/><ul className="check-list">{t.pain.map(x=><li key={x}>{x}</li>)}</ul></div></section><section className="section tinted"><SectionHead center eyebrow="WHAT WE DO" title={t.servicesTitle} text={t.servicesText}/><div className="cards services">{t.services.map(([a,b],i)=><article className="service-card" key={a}><span className="card-no">0{i+1}</span><h3>{a}</h3><p>{b}</p><Link to="/services">{t.more} <b>←</b></Link></article>)}</div></section><section className="section"><SectionHead eyebrow="WHO WE SERVE" title={t.serveTitle} text={t.serveText}/><div className="audience-grid">{t.audiences.map((x,i)=><Link to="/who-we-serve" className="audience-card" key={x}><span>0{i+1}</span><h3>{x}</h3><b>↗</b></Link>)}</div></section><section className="section process-area"><div><SectionHead eyebrow="THE DIFFERENCE" title={t.whyTitle} text={t.whyText}/><Button to="/about">{t.nav[1]}</Button></div><div className="process">{t.process.map(([n,a,b])=><article key={n}><span>{n}</span><h3>{a}</h3><p>{b}</p></article>)}</div></section><section className="section insights-preview"><SectionHead eyebrow="INSIGHTS" title={t.insightsTitle}/><ArticleGrid t={t} limit={3}/><Link className="text-link" to="/insights">{t.nav[4]} <b>←</b></Link></section><section className="section faq"><SectionHead center eyebrow="FAQ" title={t.faqTitle}/><div className="faq-list">{t.faq.map(([q,a],i)=><div className={faq===i?'expanded':''} key={q}><button onClick={()=>setFaq(faq===i?null:i)} aria-expanded={faq===i}>{q}<b>{faq===i?'−':'+'}</b></button>{faq===i&&<p>{a}</p>}</div>)}</div></section><CTA t={t}/></main></> }
function ArticleGrid({t,limit,filter=''}) { return <div className="article-grid">{articles.filter(a=>(a.title+a.excerpt+a.cat).toLowerCase().includes(filter.toLowerCase())).slice(0,limit).map((a,i)=><article className="article-card" key={a.slug}><span>{a.cat}</span><h3>{a.title}</h3><p>{a.excerpt}</p><Link to={'/insights/'+a.slug}>{t.read} <b>←</b></Link></article>)}</div> }
function CTA({t}) { return <section className="cta"><div><span className="eyebrow">START WITH CLARITY</span><h2>{t.ctaTitle}</h2><p>{t.ctaText}</p></div><Button to="/contact">{t.book}</Button></section> }
function PageHero({eyebrow,title,text}) { return <section className="page-hero"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></section> }
function About({t,lang}) { return <><SEO lang={lang} title={t.nav[1]} description={t.aboutText} crumbs={[{name:'Home',path:'/'},{name:'About',path:'/about'}]}/><main><PageHero eyebrow="ABOUT MOATH HAMMAD" title={t.aboutTitle} text={t.aboutText}/><section className="section"><div className="statement"><span>MH</span><blockquote>“The best financial support gives owners room to focus on the work only they can do.”</blockquote></div><div className="cards value-cards">{t.aboutCards.map(([a,b])=><article key={a}><h3>{a}</h3><p>{b}</p></article>)}</div></section><CTA t={t}/></main></> }
function Services({t,lang}) { return <><SEO lang={lang} title={t.nav[2]} description={t.servicesPageText} crumbs={[{name:'Home',path:'/'},{name:'Services',path:'/services'}]}/><main><PageHero eyebrow="SERVICES" title={t.servicesPageTitle} text={t.servicesPageText}/><section className="section service-details">{t.services.map(([a,b],i)=><article key={a}><span className="card-no">0{i+1}</span><div><h2>{a}</h2><p>{b}</p><ul className="check-list"><li>Clear scope aligned with your business needs</li><li>Professional, timely communication</li><li>Practical reporting and useful next steps</li></ul></div><Button to="/contact">{t.book}</Button></article>)}</section><CTA t={t}/></main></> }
function Who({t,lang}) { return <><SEO lang={lang} title={t.nav[3]} description={t.serveText} crumbs={[{name:'Home',path:'/'},{name:'Who We Serve',path:'/who-we-serve'}]}/><main><PageHero eyebrow="WHO WE SERVE" title={t.servePageTitle} text={t.serveText}/><section className="section sector-list">{t.audiences.map((x,i)=><article key={x}><span>0{i+1}</span><h2>{x}</h2><p>{i===0?'Keep the pace of service while developing a clearer view of daily sales, costs and cash.':i===1?'Bring consistency to high-volume, ingredient-led operations and their financial records.':'Establish financial structure that makes everyday decisions and future growth easier.'}</p></article>)}</section><CTA t={t}/></main></> }
function Insights({t,lang}) { const [filter,setFilter]=useState(''); return <><SEO lang={lang} title={t.nav[4]} description={t.insightPageTitle} crumbs={[{name:'Home',path:'/'},{name:'Insights',path:'/insights'}]}/><main><PageHero eyebrow="INSIGHTS" title={t.insightPageTitle} text={t.homeDesc}/><section className="section"><div className="search"><span>{icons.search}</span><input aria-label={t.search} placeholder={t.search} value={filter} onChange={e=>setFilter(e.target.value)}/></div><ArticleGrid t={t} filter={filter}/>{!articles.some(a=>(a.title+a.excerpt+a.cat).toLowerCase().includes(filter.toLowerCase()))&&<p className="empty">{t.noResults}</p>}</section></main></> }
function Article({t,lang,slug}) { const a=articles.find(x=>x.slug===slug); if(!a)return <NotFound t={t} lang={lang}/>; return <><SEO lang={lang} type="article" title={a.title} description={a.excerpt} crumbs={[{name:'Home',path:'/'},{name:'Insights',path:'/insights'},{name:a.title,path:'/insights/'+a.slug}]}/><main><article className="article-detail"><span className="eyebrow">{a.cat}</span><h1>{a.title}</h1><p className="lead">{a.excerpt}</p><div className="article-body"><p>Good financial habits do not need to make business ownership more complicated. They should make the next decision easier to see.</p><h2>Start with a useful routine</h2><p>Set a consistent time to review the information that matters to your operations. Accurate records and timely financial reporting give you a better base for decisions in the UAE market.</p><h2>Make the numbers actionable</h2><p>The goal is not simply to collect reports. It is to use a clear view of activity, costs and cash to ask better questions and take measured action.</p></div><Link to="/insights" className="text-link">← {t.nav[4]}</Link></article></main></> }
function Contact({t,lang}) { const [sent,setSent]=useState(false); const submit=e=>{e.preventDefault();setSent(true)}; return <><SEO lang={lang} title={t.nav[5]} description={t.contactText} crumbs={[{name:'Home',path:'/'},{name:'Contact',path:'/contact'}]}/><main><PageHero eyebrow="CONTACT" title={t.contactTitle} text={t.contactText}/><section className="section contact-layout"><form onSubmit={submit}>{[['name',t.name,'text'],['business',t.business,'text'],['email',t.email,'email'],['phone',t.phone,'tel']].map(([n,l,type])=><label key={n}>{l}<input required type={type} aria-label={l} name={n}/></label>)}<label>{t.message}<textarea required aria-label={t.message} rows="5"/></label><button className="button" type="submit">{t.send}<span>{icons.arrow}</span></button>{sent&&<p className="form-success" role="status">{t.sent}</p>}</form><aside className="contact-aside"><h2>{t.book}</h2><p>{t.ctaText}</p><a className="whatsapp" href="https://wa.me/[PHONE_NUMBER]" target="_blank" rel="noreferrer">◉ {t.whatsapp}</a><dl><dt>{t.phone}</dt><dd>[PHONE NUMBER]</dd><dt>{t.email}</dt><dd>[EMAIL]</dd><dt>Office</dt><dd>[OFFICE ADDRESS]</dd></dl></aside></section></main></> }
function NotFound({t,lang}) { return <><SEO lang={lang} title="404 — Page not found" description={t.notFound}/><main className="not-found"><span>404</span><h1>{t.notFound}</h1><Button to="/">{t.backHome}</Button></main></> }
export function App(){ const [lang,setLang]=useState('ar'); const [path,setPath]=useState(location.hash.slice(1)||'/'); useEffect(()=>{const f=()=>setPath(location.hash.slice(1)||'/');addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f)},[]); const t=content[lang]; let page=path==='/'?<Home t={t} lang={lang}/>:path==='/about'?<About t={t} lang={lang}/>:path==='/services'?<Services t={t} lang={lang}/>:path==='/who-we-serve'?<Who t={t} lang={lang}/>:path==='/insights'?<Insights t={t} lang={lang}/>:path==='/contact'?<Contact t={t} lang={lang}/>:path.startsWith('/insights/')?<Article t={t} lang={lang} slug={path.split('/').pop()}/>:<NotFound t={t} lang={lang}/>; return <><Header t={t} lang={lang} setLang={setLang}/>{page}<Footer t={t}/></> }
createRoot(document.getElementById('root')).render(<App/>);
