import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import './additions.css';

// TODO: insert real WhatsApp number before launch.
const WHATSAPP_URL = 'https://wa.me/000000000000';

const content = {
  ar: {
    brand: 'معاذ حماد', tag: 'للمحاسبة والتدقيق', nav: ['الرئيسية', 'من نحن', 'الخدمات', 'من نخدم', 'الرؤى', 'تواصل'],
    book: 'احجز استشارتك المجانية (15 دقيقة)', more: 'اكتشف خدماتنا', whatsapp: 'تواصل واتساب',
    homeTitle: 'محاسبك اللي يفهمك... مو بس يحسب لك.',
    homeDesc: 'دعم محاسبي وضريبي واضح لأصحاب الشركات الصغيرة والمتوسطة في الإمارات، بخبرة تتجاوز 10 سنوات.',
    heroEyebrow: 'وضوح مالي يبدأ من أول محادثة', heroTitle: 'محاسبك اللي يفهمك... مو بس يحسب لك.',
    heroText: 'دعم محاسبي وضريبي واضح لأصحاب الشركات الصغيرة والمتوسطة في الإمارات — بخبرة تتجاوز 10 سنوات، بأسلوب يشرح لك كل رقم بدل ما يعقّده.',
    heroDocument: 'وضوح مالي', heroTrust: '+10 سنوات خبرة محاسبية وضريبية | استشارة أولى مجانية',
    trust: [['الدقة', 'تفاصيل صحيحة لقرارات متوازنة'], ['الوضوح', 'تقارير تتحدث بلغة الأعمال'], ['تركيز الإمارات', 'دعم يتماشى مع واقع السوق'], ['الموثوقية', 'التزام مستمر يمكنك الاعتماد عليه']],
    painTitle: 'هل تُدير العمل، أم تبحث عن أرقامه؟', painText: 'عندما تتراكم الفواتير وتتأخر التسويات، يصبح اتخاذ القرار أصعب مما يجب. نضع نظاماً بسيطاً يترك لك مساحة للعمل والنمو.',
    pain: ['مبيعات يومية بلا صورة واضحة للربحية', 'مصروفات وفواتير تحتاج إلى تنظيم منتظم', 'تقارير متأخرة لا تساعدك على التصرف في الوقت المناسب'],
    servicesTitle: 'دعم مالي مناسب لمرحلة عملك', servicesText: 'خدمات عملية تبدأ من الأساسيات وتبني الثقة في كل رقم.', servicesEyebrow: 'ماذا نقدم',
    services: [
      ['خدمات المحاسبة', 'إمساك دفاتر دقيق، تسويات دورية، وتقارير شهرية واضحة — عشان توصلك الأرقام مفهومة قبل لا تحتاجها في قرار مهم، مو بعده.'],
      ['خدمات التدقيق', 'مراجعة مهنية ومنظمة تكشف لك الصورة بوضوح وتعزز موثوقية بياناتك — عشان تتحرك وأنت متأكد أن أرقامك جاهزة لأي متطلب.'],
      ['الدعم المالي والتجاري', 'رؤية عملية للسيولة والميزانيات والقرارات اليومية — عشان تعرف وين تركز اليوم وتخطط لخطوتك الجاية بثقة.']
    ],
    aboutTitle: 'المحاسبة الدقيقة مو رفاهية... هي أساس كل قرار تاخذه.',
    aboutText: 'أنا معاذ حماد، ومن أكثر من 10 سنين أساعد أصحاب الشركات في الإمارات يفهمون وضعهم المالي بدون تعقيد. مو بس نمسك دفاترك صح — إحنا نشرح لك كل رقم بلغة بسيطة، ونطمّنك قبل لا يصير عندك أي مفاجأة.',
    aboutEyebrow: 'عن معاذ حماد', aboutMore: 'تعرّف علينا أكثر',
    testimonialsTitle: 'عملاؤنا يتكلمون', testimonialsEyebrow: 'تجارب من واقع العمل',
    testimonials: [
      ['“صار عندي فهم فعلي لتدفقاتي النقدية، وصرت آخذ قراراتي وأنا مطمئن.”', 'أحمد — صاحب شركة خدمات'],
      ['“التقارير صارت واضحة وبسيطة، وكل سؤال له جواب في وقته.”', 'سارة — مؤسسة شركة ناشئة'],
      ['“رتبوا لنا الحسابات من البداية وخففوا علينا ضغط الالتزامات الضريبية.”', 'مالك — صاحب مطعم']
    ],
    serveTitle: 'نفهم طريقة عملك', serveText: 'نصمم الدعم المالي حول واقع عملياتك، لا حول قالب عام.', serveEyebrow: 'من نخدم', audiences: ['المطاعم', 'المخابز', 'الشركات الصغيرة', 'الشركات الناشئة', 'الشركات المتنامية'],
    whyTitle: 'شراكة مالية هادئة وواضحة', whyText: 'لا نكتفي بإتمام المهام. نرتب الأولويات، نفسّر الأرقام، ونبني أساساً أفضل للخطوة التالية.', whyEyebrow: 'الفرق الذي نقدمه', process: [['01', 'نفهم', 'نبدأ بسماع واقع عملك وأهدافك.'], ['02', 'نقيّم', 'نراجع البيانات والعمليات الحالية بوضوح.'], ['03', 'ندعم', 'ننفذ نظاماً مالياً مناسباً ومستداماً.'], ['04', 'تنمو بثقة', 'نقدّم رؤية تساعدك على التحرك بوعي.']],
    insightsTitle: 'رؤى تساعدك على اتخاذ قرار أفضل', insightsEyebrow: 'الرؤى', faqTitle: 'أسئلة شائعة', faqEyebrow: 'إجابات واضحة قبل أن تبدأ',
    faq: [
      ['هل الاستشارة الأولى فعلاً مجانية؟', 'إيه، الاستشارة الأولى مجانية بالكامل ومالها أي التزام. الهدف إنك تطمّن على وضعك قبل لا تاخذ أي قرار.'],
      ['كم تاخذ مدة تجهيز حساباتي؟', 'يعتمد على حجم شركتك ووضعها الحالي، لكن غالبًا نقدر نعطيك صورة أولية واضحة خلال أول أسبوع من التعاقد.'],
      ['هل تتعاملون مع شركات في المناطق الحرة (Free Zone)؟', 'إيه، عندنا خبرة خاصة بمتطلبات الامتثال المختلفة للمناطق الحرة في الإمارات.'],
      ['بياناتي المالية بتكون محمية قد إيه؟', 'السرية أساس شغلنا. بياناتك ما تنشارك مع أي جهة إلا بموافقتك، وكل التعامل يكون موثّق ومهني بالكامل.'],
      ['وش يميزكم عن مكتب محاسبة تاني؟', 'إحنا ما نكتفي بتسليم تقرير جاف. نشرح لك كل رقم بلغة تفهمها، ونتابع معك بشكل استباقي قبل أي موعد ضريبي مهم.'],
      ['هل الخدمة مناسبة لشركة حديثة التأسيس؟', 'بالضبط لهذا السبب أسسنا الخدمة — نساعدك تبني نظامك المالي صح من أول يوم، بدل ما تصلحه بعدين.']
    ],
    ctaEyebrow: 'ابدأ بوضوح', ctaTitle: 'وضّح وضعك المالي في 15 دقيقة بس.', ctaText: 'استشارة أولى مجانية بالكامل، بدون أي التزام. نراجع وضعك سوا ونقول لك بصراحة وين تقف.', guarantee: 'استشارة أولى مجانية بالكامل، بدون أي التزام.', ctaButton: 'احجز استشارتك المجانية الآن →',
    footerText: 'خدمات محاسبة وتدقيق عملية لأصحاب الأعمال في دولة الإمارات.', allRights: 'جميع الحقوق محفوظة.', privacy: 'سياسة الخصوصية', disclaimer: 'إخلاء المسؤولية', navigate: 'التنقل', contactLabel: 'تواصل', office: 'المكتب',
    servicesPageTitle: 'خدمات تبدأ من التفاصيل وتنتهي برؤية أوضح.', servicesPageText: 'اختر مستوى الدعم الذي يناسب عملياتك اليوم، مع مرونة للنمو غداً.', serviceBullets: ['نطاق عمل واضح يتوافق مع احتياجات شركتك', 'تواصل مهني وفي الوقت المناسب', 'تقارير عملية وخطوات تالية مفيدة'],
    servePageTitle: 'دعم مالي يفهم تحديات قطاعك.', insightPageTitle: 'رؤى مالية عملية لأعمال الإمارات.', contactTitle: 'لنبدأ محادثة مفيدة.', contactText: 'شاركنا احتياجك وسنتواصل معك لمناقشة الخطوة الأنسب.', send: 'أرسل الطلب', name: 'الاسم الكامل', business: 'اسم الشركة', email: 'البريد الإلكتروني', phone: 'رقم الهاتف', message: 'كيف يمكننا المساعدة؟', sent: 'شكراً لك. تم استلام طلبك وسنتواصل معك قريباً.',
    search: 'ابحث في المقالات...', noResults: 'لم نجد مقالات مطابقة.', read: 'اقرأ المقال', backHome: 'العودة للرئيسية', notFound: 'الصفحة التي تبحث عنها غير متاحة أو ربما تم نقلها.',
    sectorDescriptions: ['حافظ على سرعة الخدمة مع رؤية أوضح للمبيعات اليومية والتكاليف والسيولة.', 'نظّم عملياتك كثيرة الحركة وسجلاتك المالية بطريقة ثابتة وواضحة.', 'ابنِ هيكلاً مالياً يجعل قرارات اليوم وخطط النمو أسهل.'],
    articleBody: ['العادات المالية الجيدة ما لازم تعقّد إدارة عملك. بالعكس، هدفها تخلي قرارك القادم أوضح وأسهل.', 'ابدأ بروتين مفيد', 'حدد وقتاً ثابتاً لمراجعة المعلومات التي تهم عملياتك. السجلات الدقيقة والتقارير في وقتها تعطيك أساساً أقوى لقراراتك في سوق الإمارات.', 'حوّل الأرقام إلى خطوات', 'الهدف مو مجرد جمع تقارير. الهدف إنك تستخدم رؤية واضحة للحركة والتكاليف والسيولة حتى تسأل أسئلة أفضل وتتحرك بثقة.']
  },
  en: {
    brand: 'Moath Hammad', tag: 'Accounting & Auditing', nav: ['Home', 'About', 'Services', 'Who We Serve', 'Insights', 'Contact'],
    book: 'Book a free consultation', more: 'Explore Services', whatsapp: 'WhatsApp us', homeTitle: 'An accountant who understands you, not just your numbers.', homeDesc: 'Clear accounting and tax support for UAE SMEs with more than 10 years of experience.', heroEyebrow: 'Clear financial support', heroTitle: 'An accountant who understands you, not just your numbers.', heroText: 'Clear accounting and tax support for small and medium businesses in the UAE, with more than 10 years of experience.', heroDocument: 'Financial clarity', heroTrust: '10+ years of accounting and tax experience | First consultation free',
    trust: [['Accuracy', 'Reliable details for balanced decisions'], ['Clarity', 'Reports that speak your business language'], ['UAE Focus', 'Support grounded in the local market'], ['Reliability', 'Consistent care you can count on']], painTitle: 'Running the business, or chasing its numbers?', painText: 'When receipts pile up and reconciliations wait, decisions become harder than they need to be. We bring order that creates room to run and grow.', pain: ['Daily sales without a clear view of profitability', 'Expenses and invoices needing regular structure', 'Late reports that cannot support timely action'],
    servicesTitle: 'Financial support for your stage of business', servicesText: 'Practical services that build confidence in every number.', servicesEyebrow: 'What we do', services: [['Accounting Services', 'Accurate bookkeeping, regular reconciliations and clear monthly reports so the numbers reach you before an important decision, not after it.'], ['Auditing Services', 'A structured professional review that gives you a clearer picture and stronger confidence in your financial information.'], ['Financial & Business Support', 'Practical cash-flow, budget and decision support so you know where to focus today and plan your next move with confidence.']],
    aboutTitle: 'Accurate accounting is not a luxury. It is the basis for every decision.', aboutText: 'I am Moath Hammad. For more than 10 years, I have helped UAE business owners understand their financial position without unnecessary complexity. We do not simply keep your books correctly — we explain every number in plain language.', aboutEyebrow: 'About Moath Hammad', aboutMore: 'Learn more about us', testimonialsTitle: 'What our clients say', testimonialsEyebrow: 'Experiences from business owners', testimonials: [['“I have a real understanding of my cash flow and make decisions with confidence.”', 'Ahmed — service business owner'], ['“The reports are simple and clear, and every question gets a timely answer.”', 'Sara — startup founder'], ['“They organised our accounts from the start and eased our tax-compliance pressure.”', 'Restaurant owner']],
    serveTitle: 'We understand how you work', serveText: 'Our financial support is shaped around the reality of your operations — not a generic template.', serveEyebrow: 'Who we serve', audiences: ['Restaurants', 'Bakeries', 'Small Businesses', 'Startups', 'Growing Companies'], whyTitle: 'A calm, clear financial partnership', whyText: 'We do more than complete tasks. We set priorities, explain the numbers and create a stronger foundation for what comes next.', whyEyebrow: 'The difference', process: [['01', 'Understand', 'We start by listening to your business reality and goals.'], ['02', 'Assess', 'We review the current data and processes with care.'], ['03', 'Support', 'We implement a financial system that fits and lasts.'], ['04', 'Grow with confidence', 'We provide insight that supports informed action.']],
    insightsTitle: 'Insights for better business decisions', insightsEyebrow: 'Insights', faqTitle: 'Frequently asked questions', faqEyebrow: 'Clear answers before you begin', faq: [['Is the first consultation really free?', 'Yes. Your first consultation is completely free and comes with no obligation.'], ['How long will it take to prepare my accounts?', 'It depends on the size and current position of your company, but we can usually provide an initial clear picture during the first week.'], ['Do you work with companies in free zones?', 'Yes, we have experience with the different compliance requirements of UAE free zones.'], ['How protected is my financial data?', 'Confidentiality is fundamental to our work. Your data is never shared without your approval.'], ['What makes you different from another accounting firm?', 'We do not simply deliver a dry report. We explain every number in plain language and follow up proactively.'], ['Is this service suitable for a newly established company?', 'Absolutely. We help you build your financial system correctly from day one.']],
    ctaEyebrow: 'Start with clarity', ctaTitle: 'Clarify your financial position in just 15 minutes.', ctaText: 'Your first consultation is completely free, with no obligation. We will review your position together and tell you honestly where you stand.', guarantee: 'First consultation completely free, with no obligation.', ctaButton: 'Book your free consultation now →', footerText: 'Practical accounting and auditing services for UAE business owners.', allRights: 'All rights reserved.', privacy: 'Privacy Policy', disclaimer: 'Disclaimer', navigate: 'Navigate', contactLabel: 'Contact', office: 'Office',
    servicesPageTitle: 'Services that begin with detail and end in clearer direction.', servicesPageText: 'Choose support that fits your operations today, with the flexibility to grow tomorrow.', serviceBullets: ['A clear scope aligned with your business needs', 'Professional, timely communication', 'Practical reporting and useful next steps'], servePageTitle: 'Financial support that understands your sector.', insightPageTitle: 'Practical financial insights for UAE businesses.', contactTitle: 'Let’s start a useful conversation.', contactText: 'Tell us what you need and we will be in touch to discuss the right next step.', send: 'Send Request', name: 'Full name', business: 'Business name', email: 'Email address', phone: 'Phone number', message: 'How can we help?', sent: 'Thank you. Your request has been received and we will be in touch soon.', search: 'Search articles...', noResults: 'No matching articles found.', read: 'Read article', backHome: 'Return home', notFound: 'The page you are looking for is unavailable or may have moved.', sectorDescriptions: ['Keep the pace of service while developing a clearer view of daily sales, costs and cash.', 'Bring consistency to high-volume, ingredient-led operations and their financial records.', 'Establish financial structure that makes everyday decisions and future growth easier.'], articleBody: ['Good financial habits do not need to make business ownership more complicated. They should make the next decision easier to see.', 'Start with a useful routine', 'Set a consistent time to review the information that matters to your operations. Accurate records and timely financial reporting give you a better base for decisions in the UAE market.', 'Make the numbers actionable', 'The goal is not simply to collect reports. It is to use a clear view of activity, costs and cash to ask better questions and take measured action.']
  }
};

const paths = { 0: '/', 1: '/about', 2: '/services', 3: '/who-we-serve', 4: '/insights', 5: '/contact' };
const icons = { arrow: '→', menu: '☰', close: '×', search: '⌕' };
const articles = {
  ar: [
    { slug: 'cash-flow-basics', cat: 'نصائح محاسبية', title: 'أساسيات التدفق النقدي: رؤية أسبوعية أوضح لعملك', excerpt: 'إيقاع بسيط يساعدك على رؤية ما يدخل وما يخرج وما يحتاج إلى انتباه.' },
    { slug: 'restaurant-numbers', cat: 'محاسبة المطاعم', title: 'الأرقام التي يحتاج أصحاب المطاعم لمراجعتها كل أسبوع', excerpt: 'ركّز على المؤشرات التي تجعل إدارة عملياتك اليومية أسهل.' },
    { slug: 'reporting-uae', cat: 'التمويل التجاري في الإمارات', title: 'ليش التقارير المالية في وقتها مهمة للشركات في الإمارات', excerpt: 'التقارير الموثوقة تعطيك الرؤية التي تحتاجها لقرارات أهدأ وأكثر وعياً.' }
  ],
  en: [
    { slug: 'cash-flow-basics', cat: 'Accounting Tips', title: 'Cash flow basics: a clearer weekly view for your business', excerpt: 'A simple rhythm for seeing what is coming in, going out and what needs attention.' },
    { slug: 'restaurant-numbers', cat: 'Restaurant Accounting', title: 'The numbers restaurant owners should review each week', excerpt: 'Focus your attention on the measures that make your daily operations easier to manage.' },
    { slug: 'reporting-uae', cat: 'UAE Business Finance', title: 'Why timely financial reporting matters for UAE businesses', excerpt: 'Reliable reporting provides the visibility needed for calmer, more informed decisions.' }
  ]
};

function Link({ to, children, className = '', onClick }) { return <a href={'#' + to} className={className} onClick={onClick}>{children}</a>; }
function Button({ to = '/contact', children, secondary = false, className = '', onClick }) { return <Link to={to} className={`button ${secondary ? 'button-secondary' : ''} ${className}`} onClick={onClick}>{children}<span aria-hidden>{icons.arrow}</span></Link>; }
function BrandMark() { return <svg className="brand-mark" viewBox="0 0 112 70" aria-hidden="true"><path fill="currentColor" d="M5 64V5l35 35L60 20v24L40 64 18 42v22H5Z"/><path fill="currentColor" d="M69 64V28h34V5h12v59h-12V40H81v24H69Z"/><path className="mark-sage" d="M69 17 87 0v18L69 35V17Zm35-12h9v59h-9V5Z"/></svg>; }
function SEO({ title, description, lang, type = 'website', crumbs = [] }) { useEffect(() => { const full = `${title} | Moath Hammad Accounting & Auditing`; document.title = full; document.documentElement.lang = lang; document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr'; const base = 'https://moathhammad.ae'; const canonical = base + (location.hash.slice(1) || '/'); const set = (n, v, p = 'name') => { let e = document.head.querySelector(`meta[${p}="${n}"]`); if (!e) { e = document.createElement('meta'); e.setAttribute(p, n); document.head.append(e); } e.content = v; }; set('description', description); set('og:title', full, 'property'); set('og:description', description, 'property'); set('og:type', type, 'property'); set('og:url', canonical, 'property'); let c = document.head.querySelector('link[rel="canonical"]'); if (!c) { c = document.createElement('link'); c.rel = 'canonical'; document.head.append(c); } c.href = canonical; const schema = [{ '@context': 'https://schema.org', '@type': ['Organization', 'ProfessionalService'], name: 'Moath Hammad Accounting & Auditing', description, url: base, areaServed: { '@type': 'Country', name: 'United Arab Emirates' } }, crumbs.length && { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: crumbs.map((x, i) => ({ '@type': 'ListItem', position: i + 1, name: x.name, item: base + x.path })) }].filter(Boolean); let el = document.getElementById('page-schema'); if (!el) { el = document.createElement('script'); el.type = 'application/ld+json'; el.id = 'page-schema'; document.head.append(el); } el.textContent = JSON.stringify(schema); }, [title, description, lang, type, crumbs]); return null; }
function Header({ t, lang, setLang }) {
  const [open, setOpen] = useState(false);
  const toggleRef = useRef(null);
  const wasOpenRef = useRef(false);
  const navItems = [[0, 0], [2, 2], [1, 1], [5, 5]];
  const closeMenu = () => setOpen(false);
  const changeLanguage = () => { setLang(lang === 'ar' ? 'en' : 'ar'); closeMenu(); };

  useEffect(() => {
    if (!open) {
      if (wasOpenRef.current) {
        wasOpenRef.current = false;
        requestAnimationFrame(() => toggleRef.current?.focus());
      }
      return undefined;
    }

    wasOpenRef.current = true;
    const onKeyDown = event => { if (event.key === 'Escape') closeMenu(); };
    document.body.classList.add('overflow-hidden');
    document.addEventListener('keydown', onKeyDown);
    return () => {
      document.body.classList.remove('overflow-hidden');
      document.removeEventListener('keydown', onKeyDown);
    };
  }, [open]);

  const navLinks = (onClick) => <>{navItems.map(([label, path]) => <Link key={t.nav[label]} to={paths[path]} onClick={onClick}>{t.nav[label]}</Link>)}<button className="language" onClick={changeLanguage} aria-label="Change language">AR <i/> EN</button><Button onClick={onClick}>{t.book}</Button></>;

  return <><header className="site-header"><div className="nav-wrap"><Link to="/" className="logo" onClick={closeMenu}><BrandMark/><span><b>MO'ATH HAMMAD</b><small>ACCOUNTING &amp; TAX AUDIT</small></span></Link><nav className="desktop-nav" aria-label="Primary navigation">{navLinks()}</nav></div></header><button ref={toggleRef} className="menu-toggle md:hidden" type="button" aria-label={open ? 'Close navigation' : 'Open navigation'} aria-controls="mobile-navigation" aria-expanded={open} onClick={() => setOpen(value => !value)}><span className="hamburger-lines" aria-hidden="true"><i/><i/><i/></span></button><div className={`drawer-scrim ${open ? 'is-open' : ''}`} aria-hidden={!open} onClick={closeMenu}/><nav id="mobile-navigation" className={`mobile-drawer ${open ? 'is-open' : ''}`} aria-label="Mobile navigation" aria-hidden={!open}>{navLinks(closeMenu)}</nav></>;
}
function Footer({ t }) { return <footer><div className="footer-grid"><div><Link to="/" className="logo"><BrandMark/><span><b>MO'ATH HAMMAD</b><small>ACCOUNTING &amp; TAX AUDIT</small></span></Link><p>{t.footerText}</p><div className="footer-trust" aria-label="Trust badges"><span>✓ {t.lang === 'ar' ? '+10 سنوات خبرة' : '10+ years experience'}</span>{/* TODO: insert real license/registration badge image */}<span className="license-badge">✓ {t.lang === 'ar' ? 'ترخيص مهني / تسجيل FTA' : 'Professional license / FTA registration'}</span></div></div><div><h3>{t.navigate}</h3><Link to="/about">{t.nav[1]}</Link><Link to="/services">{t.nav[2]}</Link><Link to="/insights">{t.nav[4]}</Link></div><div><h3>{t.contactLabel}</h3><a href="tel:[PHONE NUMBER]">[PHONE NUMBER]</a><a href="mailto:[EMAIL]">[EMAIL]</a><span>[OFFICE ADDRESS]</span></div></div><div className="footer-bottom"><span>© 2026 {t.brand}. {t.allRights}</span><span><a href="#/privacy">{t.privacy}</a> · <a href="#/disclaimer">{t.disclaimer}</a></span></div></footer>; }
function FloatingWhatsApp({ t }) { return <a className="floating-whatsapp" href={WHATSAPP_URL} target="_blank" rel="noreferrer" aria-label={t.whatsapp} title={t.whatsapp}><svg viewBox="0 0 32 32" aria-hidden="true"><path fill="currentColor" d="M16 2.8A13.1 13.1 0 0 0 4.8 22.7L3 29l6.5-1.7A13.2 13.2 0 1 0 16 2.8Zm0 23.9c-2 0-3.9-.5-5.6-1.5l-.4-.2-3.8 1 1-3.7-.3-.4a10.6 10.6 0 1 1 9.1 4.8Zm5.8-7.9c-.3-.2-1.8-.9-2-1-.3-.1-.5-.2-.7.2s-.8 1-1 1.2c-.2.2-.4.2-.7.1-1.8-.9-3-2.4-3.3-2.9-.2-.3 0-.5.1-.6l.5-.5c.2-.2.2-.4.3-.6.1-.2 0-.5 0-.6-.1-.2-.7-1.7-1-2.3-.2-.6-.5-.5-.7-.5h-.6c-.2 0-.6.1-.9.5s-1.2 1.1-1.2 2.8 1.2 3.3 1.4 3.5c.2.2 2.4 3.7 5.8 5.1.8.4 1.5.6 2 .7.8.3 1.5.2 2.1.1.6-.1 1.8-.7 2.1-1.4.3-.7.3-1.3.2-1.4 0-.2-.3-.3-.6-.5Z"/></svg><span>{t.whatsapp}</span></a>; }
function SectionHead({ eyebrow, title, text, center = false }) { return <div className={`section-head ${center ? 'center' : ''}`}><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{text && <p>{text}</p>}</div>; }
function Hero({ t }) { return <><section className="hero"><div className="hero-workspace" aria-hidden="true"/><div className="hero-copy"><span className="eyebrow">{t.heroEyebrow}</span><h1>{t.heroTitle}</h1><p>{t.heroText}</p><div className="actions"><Button>{t.book}</Button><a className="button button-secondary" href={WHATSAPP_URL} target="_blank" rel="noreferrer">{t.whatsapp}<span aria-hidden>↗</span></a></div><p className="hero-trust">✓ {t.heroTrust}</p></div><div className="hero-art" aria-hidden="true"><div className="hero-document"><span>MO'ATH HAMMAD</span><b>{t.heroDocument}</b><i/></div><div className="hero-seal"><BrandMark/></div></div></section><section className="trust-strip">{t.trust.map(([title, text]) => <div key={title}><strong>{title}</strong><span>{text}</span></div>)}</section></>; }
function AboutPreview({ t }) { return <section className="section about-preview"><div className="about-monogram" aria-hidden="true">MH</div><div><SectionHead eyebrow={t.aboutEyebrow} title={t.aboutTitle} text={t.aboutText}/><Button secondary to="/about">{t.aboutMore}</Button></div></section>; }
function Testimonials({ t }) { return <section className="section tinted testimonials"><SectionHead center eyebrow={t.testimonialsEyebrow} title={t.testimonialsTitle}/>{/* TODO: replace with real client testimonials */}<div className="testimonial-grid">{t.testimonials.map(([quote, client]) => <article className="testimonial-card" key={client}><span className="stars" aria-label="5 stars">★★★★★</span><blockquote>{quote}</blockquote><p>✓ {client}</p></article>)}</div></section>; }
function Home({ t, lang }) { const [faq, setFaq] = useState(null); useEffect(() => { let el = document.getElementById('faq-schema'); if (!el) { el = document.createElement('script'); el.id = 'faq-schema'; el.type = 'application/ld+json'; document.head.append(el); } el.textContent = JSON.stringify({ '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: t.faq.map(([q, a]) => ({ '@type': 'Question', name: q, acceptedAnswer: { '@type': 'Answer', text: a } })) }); }, [t]); return <><SEO lang={lang} title={t.homeTitle} description={t.homeDesc} crumbs={[{ name: t.nav[0], path: '/' }]}/><Hero t={t}/><main><section className="section pain"><div className="pain-art"><span>UAE</span></div><div><SectionHead eyebrow={lang === 'ar' ? 'مصمم لأصحاب الأعمال' : 'Built for business owners'} title={t.painTitle} text={t.painText}/><ul className="check-list">{t.pain.map(x => <li key={x}>{x}</li>)}</ul></div></section><section className="section tinted"><SectionHead center eyebrow={t.servicesEyebrow} title={t.servicesTitle} text={t.servicesText}/><div className="cards services">{t.services.map(([name, desc], i) => <article className="service-card" key={name}><span className="card-no">0{i + 1}</span><h3>{name}</h3><p>{desc}</p><Link to="/services">{t.more} <b>←</b></Link></article>)}</div></section><AboutPreview t={t}/><Testimonials t={t}/><section className="section"><SectionHead eyebrow={t.serveEyebrow} title={t.serveTitle} text={t.serveText}/><div className="audience-grid">{t.audiences.map((name, i) => <Link to="/who-we-serve" className="audience-card" key={name}><span>0{i + 1}</span><h3>{name}</h3><b>↗</b></Link>)}</div></section><section className="section process-area"><div><SectionHead eyebrow={t.whyEyebrow} title={t.whyTitle} text={t.whyText}/><Button to="/about">{t.nav[1]}</Button></div><div className="process">{t.process.map(([n, title, description]) => <article key={n}><span>{n}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section><section className="section insights-preview"><SectionHead eyebrow={t.insightsEyebrow} title={t.insightsTitle}/><ArticleGrid t={t} lang={lang} limit={3}/><Link className="text-link" to="/insights">{t.nav[4]} <b>←</b></Link></section><section className="section faq"><SectionHead center eyebrow={t.faqEyebrow} title={t.faqTitle}/><div className="faq-list">{t.faq.map(([q, a], i) => <div className={faq === i ? 'expanded' : ''} key={q}><button onClick={() => setFaq(faq === i ? null : i)} aria-expanded={faq === i}>{q}<b>{faq === i ? '−' : '+'}</b></button>{faq === i && <p>{a}</p>}</div>)}</div></section><CTA t={t}/></main></>; }
function ArticleGrid({ t, lang, limit, filter = '' }) { const all = articles[lang]; return <div className="article-grid">{all.filter(a => (a.title + a.excerpt + a.cat).toLowerCase().includes(filter.toLowerCase())).slice(0, limit).map(a => <article className="article-card" key={a.slug}><span>{a.cat}</span><h3>{a.title}</h3><p>{a.excerpt}</p><Link to={`/insights/${a.slug}`}>{t.read} <b>←</b></Link></article>)}</div>; }
function CTA({ t }) { return <section className="cta"><div><span className="eyebrow">{t.ctaEyebrow}</span><h2>{t.ctaTitle}</h2><p>{t.ctaText}</p><p className="guarantee">✓ {t.guarantee}</p></div><Button>{t.ctaButton}</Button></section>; }
function PageHero({ eyebrow, title, text }) { return <section className="page-hero"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></section>; }
function About({ t, lang }) { return <><SEO lang={lang} title={t.nav[1]} description={t.aboutText} crumbs={[{ name: t.nav[0], path: '/' }, { name: t.nav[1], path: '/about' }]}/><main><PageHero eyebrow={t.aboutEyebrow} title={t.aboutTitle} text={t.aboutText}/><section className="section about-page"><div className="about-monogram" aria-hidden="true">MH</div><div className="cards value-cards">{[[lang === 'ar' ? 'وضوح في كل خطوة' : 'Clarity at every step', lang === 'ar' ? 'نشرح ما يهمك بلغة مباشرة، مع تفاصيل تدعم القرار.' : 'We explain what matters in direct language, with detail that supports decisions.'], [lang === 'ar' ? 'منهج منظم' : 'A structured approach', lang === 'ar' ? 'نبني العمليات على الدقة والاستمرارية وقابلية المتابعة.' : 'We build around accuracy, consistency and easy follow-through.'], [lang === 'ar' ? 'تركيز على عملك' : 'Business-led support', lang === 'ar' ? 'الدعم المالي مصمم ليخدم واقع عملك في دولة الإمارات.' : 'Financial support designed around your UAE operating reality.']].map(([title, text]) => <article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></section><CTA t={t}/></main></>; }
function Services({ t, lang }) { return <><SEO lang={lang} title={t.nav[2]} description={t.servicesPageText} crumbs={[{ name: t.nav[0], path: '/' }, { name: t.nav[2], path: '/services' }]}/><main><PageHero eyebrow={t.servicesEyebrow} title={t.servicesPageTitle} text={t.servicesPageText}/><section className="section service-details">{t.services.map(([name, desc], i) => <article key={name}><span className="card-no">0{i + 1}</span><div><h2>{name}</h2><p>{desc}</p><ul className="check-list">{t.serviceBullets.map(bullet => <li key={bullet}>{bullet}</li>)}</ul></div><Button>{t.book}</Button></article>)}</section><CTA t={t}/></main></>; }
function Who({ t, lang }) { return <><SEO lang={lang} title={t.nav[3]} description={t.serveText} crumbs={[{ name: t.nav[0], path: '/' }, { name: t.nav[3], path: '/who-we-serve' }]}/><main><PageHero eyebrow={t.serveEyebrow} title={t.servePageTitle} text={t.serveText}/><section className="section sector-list">{t.audiences.map((name, i) => <article key={name}><span>0{i + 1}</span><h2>{name}</h2><p>{t.sectorDescriptions[Math.min(i, 2)]}</p></article>)}</section><CTA t={t}/></main></>; }
function Insights({ t, lang }) { const [filter, setFilter] = useState(''); const noResults = !articles[lang].some(a => (a.title + a.excerpt + a.cat).toLowerCase().includes(filter.toLowerCase())); return <><SEO lang={lang} title={t.nav[4]} description={t.insightPageTitle} crumbs={[{ name: t.nav[0], path: '/' }, { name: t.nav[4], path: '/insights' }]}/><main><PageHero eyebrow={t.insightsEyebrow} title={t.insightPageTitle} text={t.homeDesc}/><section className="section"><div className="search"><span>{icons.search}</span><input aria-label={t.search} placeholder={t.search} value={filter} onChange={e => setFilter(e.target.value)}/></div><ArticleGrid t={t} lang={lang} filter={filter}/>{noResults && <p className="empty">{t.noResults}</p>}</section></main></>; }
function Article({ t, lang, slug }) { const article = articles[lang].find(item => item.slug === slug); if (!article) return <NotFound t={t} lang={lang}/>; const [intro, headingOne, bodyOne, headingTwo, bodyTwo] = t.articleBody; return <><SEO lang={lang} type="article" title={article.title} description={article.excerpt} crumbs={[{ name: t.nav[0], path: '/' }, { name: t.nav[4], path: '/insights' }, { name: article.title, path: `/insights/${article.slug}` }]}/><main><article className="article-detail"><span className="eyebrow">{article.cat}</span><h1>{article.title}</h1><p className="lead">{article.excerpt}</p><div className="article-body"><p>{intro}</p><h2>{headingOne}</h2><p>{bodyOne}</p><h2>{headingTwo}</h2><p>{bodyTwo}</p></div><Link to="/insights" className="text-link">← {t.nav[4]}</Link></article></main></>; }
function Contact({ t, lang }) { const [sent, setSent] = useState(false); return <><SEO lang={lang} title={t.nav[5]} description={t.contactText} crumbs={[{ name: t.nav[0], path: '/' }, { name: t.nav[5], path: '/contact' }]}/><main><PageHero eyebrow={t.contactLabel} title={t.contactTitle} text={t.contactText}/><section className="section contact-layout"><form onSubmit={event => { event.preventDefault(); setSent(true); }}>{[['name', t.name, 'text'], ['business', t.business, 'text'], ['email', t.email, 'email'], ['phone', t.phone, 'tel']].map(([name, label, type]) => <label key={name}>{label}<input required type={type} aria-label={label} name={name}/></label>)}<label>{t.message}<textarea required aria-label={t.message} rows="5"/></label><button className="button" type="submit">{t.send}<span>{icons.arrow}</span></button>{sent && <p className="form-success" role="status">{t.sent}</p>}</form><aside className="contact-aside"><h2>{t.book}</h2><p>{t.ctaText}</p><a className="whatsapp" href={WHATSAPP_URL} target="_blank" rel="noreferrer">◉ {t.whatsapp}</a><dl><dt>{t.phone}</dt><dd>[PHONE NUMBER]</dd><dt>{t.email}</dt><dd>[EMAIL]</dd><dt>{t.office}</dt><dd>[OFFICE ADDRESS]</dd></dl></aside></section></main></>; }
function NotFound({ t, lang }) { return <><SEO lang={lang} title="404" description={t.notFound}/><main className="not-found"><span>404</span><h1>{t.notFound}</h1><Button to="/">{t.backHome}</Button></main></>; }
export function App() { const [lang, setLang] = useState('ar'); const [path, setPath] = useState(location.hash.slice(1) || '/'); useEffect(() => { const updatePath = () => setPath(location.hash.slice(1) || '/'); addEventListener('hashchange', updatePath); return () => removeEventListener('hashchange', updatePath); }, []); const t = { ...content[lang], lang }; const page = path === '/' ? <Home t={t} lang={lang}/> : path === '/about' ? <About t={t} lang={lang}/> : path === '/services' ? <Services t={t} lang={lang}/> : path === '/who-we-serve' ? <Who t={t} lang={lang}/> : path === '/insights' ? <Insights t={t} lang={lang}/> : path === '/contact' ? <Contact t={t} lang={lang}/> : path.startsWith('/insights/') ? <Article t={t} lang={lang} slug={path.split('/').pop()}/> : <NotFound t={t} lang={lang}/>; return <><Header t={t} lang={lang} setLang={setLang}/>{page}<Footer t={t}/><FloatingWhatsApp t={t}/></>; }
createRoot(document.getElementById('root')).render(<App/>);
